import type { Metadata } from 'next'
import './globals.css'


export const metadata: Metadata = {
  title: 'Union Developers - Experiência prática e imersiva para desenvolvedores juniors',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html className='scroll-smooth' lang='en'>
      <body className={`$font-poppins antialiased bg-[#1F1D2B]`}>{children}</body>
    </html>
  )
}
